server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://shared-postgres:5432/ticketdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    server-url: ${SWAGGER_SERVER_URL:http://localhost:8080}
